const DefaultTrainings = [
  {
    id: 0,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    duration: 100,
    importand: true,
    finished: false,
  },
  {
    id: 1,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    duration: 100,
    importand: true,
    finished: false,
  },
  {
    id: 2,
    type: "running",
    description: "easy run - enjoy workout",
    date: new Date().toISOString().slice(0, 10),
    duration: 30,
    importand: true,
    finished: false,
  },
  {
    id: 3,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    duration: 100,
    importand: true,
    finished: false,
  },
  {
    id: 4,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    duration: 100,
    importand: true,
    finished: false,
  },
  {
    id: 5,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    duration: 100,
    importand: true,
    finished: false,
  },
  {
    id: 6,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    duration: 100,
    importand: true,
    finished: false,
  },
];

export default DefaultTrainings;
