const DefaultTrainings = [
  {
    id: 0,
    type: "bike",
    description: " bike intervals 3*5k hard, break - 2km slow.",
    date: "2021-09-03",
    minutes: 45,
    hours: 0,
    important: true,
    finished: false,
  },
  {
    id: 1,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    minutes: 30,
    hours: 1,
    important: true,
    finished: false,
  },
  {
    id: 2,
    type: "running",
    description: "easy run - enjoy workout",
    date: new Date().toISOString().slice(0, 10),
    minutes: 30,
    hours: 0,
    important: true,
    finished: false,
  },
  {
    id: 3,
    type: "swim",
    description: "crawl",
    date: "2021-08-20",
    minutes: 30,
    hours: 0,
    important: true,
    finished: false,
  },
  {
    id: 4,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    minutes: 30,
    hours: 0,
    important: true,
    finished: false,
  },
  {
    id: 5,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    minutes: 30,
    hours: 0,
    important: true,
    finished: false,
  },
  {
    id: 6,
    type: "running",
    description: "easy run",
    date: "2021-08-20",
    minutes: 30,
    hours: 0,
    important: true,
    finished: false,
  },
  {
    id: 7,
    type: "running",
    description: "easy run",
    date: "2021-08-01",
    minutes: 30,
    hours: 0,
    important: true,
    finished: true,
  },
];

export default DefaultTrainings;
